spring.datasource.url=jdbc:postgresql://localhost:5432/University
spring.datasource.username=PUT_DB_USER_HERE
spring.datasource.password=PUT_DB_PASSWORD_HERE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ActiveMQ (\u0438\u043b\u0438 Artemis) \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=PUT_GOOGLE_MAIL_HERE
spring.mail.password=PUT_GOOGLE_MAIL_PASSWORD_HERE
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.activemq.packages.trust-all=false
spring.activemq.packages.trusted=com.example.jms.dto,java.lang